### ISSUE TITLE
Discuss: An idea to arrange the contents on the website

### ISSUE THREAD

**Issue by ecwu** [UICHCC/uichcc.github.io#14]
我简单思考了一下该如何重新排布 [uichcc.com](https://uichcc.com) 的布局：
- 将首页现有的四页轮播内容中的后三页，移动至 About 页面。
> 移动的三页内容为：
>  - We Create.
>  - We Advocate.
>  - We Open.

- 日后有新的活动 / 新闻，通过在主页添加相应轮播来达到宣传的效果。

**Comment by billzhonggz** [comment]
Approved.
