### ISSUE TITLE
click the bottom for more information ?

### ISSUE THREAD

**Issue by TerenceLiu98** [UICHCC/uichcc.github.io#31]
The description in [Contact us](https://uichcc.com/contacts/), it should be "click the button" or just "click the bottom" :)

**Comment by ecwu** [comment]
Fixed in [commit `2f905b5` @ UICHCC/uichcc-hugo](https://github.com/UICHCC/uichcc-hugo/commit/2f905b5ee125c57ffd4b2d2edc14c6686368e820)
